library(ggmcmc)

#load the stanfit object generated by stan or jags
load("stan_marginalization_output_20warmup.Rdata")

#ggs takes both stanfit and jags output as an input
s <- ggs(fit)

#plot the graphs, genereates a pdf containing histogram, running means, autocorrelation plot etc.
#For more info: http://xavier-fim.net/packages/ggmcmc/
ggmcmc(s)
